STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.BEEQUEEN = "Bee Queen"
STRINGS.NAMES.BEEQUEENHIVE = "Honey Patch"
STRINGS.NAMES.BEEQUEENHIVEGROWING = "Somewhat Gigantic Beehive"
STRINGS.NAMES.BEEQUEENHIVEGROWN = "Gigantic Beehive"

for k, v in pairs(STRINGS.CHARACTERS) do
    v.DESCRIBE.BEEQUEENHIVE = {}
end

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEEQUEEN = "Keep that stinger away from me!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEEQUEENHIVE.GENERIC = "It's too sticky to walk on."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEEQUEENHIVE.GROWING = "Was that there before?"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEEQUEENHIVEGROWN = "How in science did it get so big?!"

STRINGS.CHARACTERS.WARLY.DESCRIBE.BEEQUEEN = "Your honey was too delicious not to steal!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.BEEQUEENHIVE.GENERIC = "I don't think that honey would taste very good."
STRINGS.CHARACTERS.WARLY.DESCRIBE.BEEQUEENHIVE.GROWING = "I don't remember this being here."
STRINGS.CHARACTERS.WARLY.DESCRIBE.BEEQUEENHIVEGROWN = "That's almost definitely bigger than before."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEEQUEEN = "Your monarchy shall topple this day!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEEQUEENHIVE.GENERIC = "A land not of milk, but of honey."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEEQUEENHIVE.GROWING = "The bees are expanding their domain."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEEQUEENHIVEGROWN = "A hive of winged warriors."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEEQUEEN = "I didn't make that one! Really!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEEQUEENHIVE.GENERIC = "I am not getting that on my shoes."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEEQUEENHIVE.GROWING = "Now what are those bees up to?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEEQUEENHIVEGROWN = "I don't see what all the buzz is about."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEEQUEEN = "Bees aren't our friends!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEEQUEENHIVE.GENERIC = "Not web. We can't walk on it."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEEQUEENHIVE.GROWING = "I wonder what the bees are making!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEEQUEENHIVEGROWN = "Oh, bother!"

STRINGS.CHARACTERS.WENDY.DESCRIBE.BEEQUEEN = "As regal as she is ruthless..."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BEEQUEENHIVE.GENERIC = "The bees left their sweet mark upon the earth."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BEEQUEENHIVE.GROWING = "It is not a danger... yet..."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BEEQUEENHIVEGROWN = "Dripping with enmity. And honey."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEEQUEEN = "The workers ferociously protect her."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEEQUEENHIVE.GENERIC = "Thick Apis mellifera honeycomb."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEEQUEENHIVE.GROWING = "The Apis mellifera are constructing a new hive."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEEQUEENHIVEGROWN = "An Apis mellifera nest of unusual size."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEEQUEEN = "No amount of honey is worth THAT!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEEQUEENHIVE.GENERIC = "It all came from a bee's butt."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEEQUEENHIVE.GROWING = "Ew, burn it before it gets any bigger!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEEQUEENHIVEGROWN = "Dare you guys to smack it with a hammer."

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEEQUEEN = "Is giant lady bee!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEEQUEENHIVE.GENERIC = "Sticky stompy patch of muck!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEEQUEENHIVE.GROWING = "Little hive is get bigger!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEEQUEENHIVEGROWN = "Wolfgang's mighty punches do nothing."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEEQUEEN = "Bees got no business getting that big."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEEQUEENHIVE.GENERIC = "I'm not eating honey off the ground."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEEQUEENHIVE.GROWING = "The bees are planning something."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEEQUEENHIVEGROWN = "Nature is something else, eh?"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BEEQUEEN = "Big Mommy Buzz!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BEEQUEENHIVE.GENERIC = "Full of Buzz Juice"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BEEQUEENHIVE.GROWING = "Getting bigger!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BEEQUEENHIVEGROWN = "Big Buzz home!"

STRINGS.CHARACTERS.WX78.DESCRIBE.BEEQUEEN = "THE PRIME BEE"
STRINGS.CHARACTERS.WX78.DESCRIBE.BEEQUEENHIVE.GENERIC = "SWEET DIRT OOZE"
STRINGS.CHARACTERS.WX78.DESCRIBE.BEEQUEENHIVE.GROWING = "THERE WILL BE BEES SOON"
STRINGS.CHARACTERS.WX78.DESCRIBE.BEEQUEENHIVEGROWN = "PROOF OF BEES' INDUSTRIOUSNESS"

-- DST only

-- WAGSTAFF
STRINGS.CHARACTERS.WAGSTAFF.DESCRIBE.BEEQUEEN = "Extraordinary! A eusocial superorganism with delusions of grandeur!"
STRINGS.CHARACTERS.WAGSTAFF.DESCRIBE.BEEQUEENHIVE.GENERIC = "A viscous secretion field. I shall not tread there."
STRINGS.CHARACTERS.WAGSTAFF.DESCRIBE.BEEQUEENHIVE.GROWING = "Fascinating! The structure is actively expanding."
STRINGS.CHARACTERS.WAGSTAFF.DESCRIBE.BEEQUEENHIVEGROWN = "Good heavens! That is an absurdly oversized apiary!"
STRINGS.CHARACTERS.WAGSTAFF.DESCRIBE.CHESSPIECE_BEEQUEEN = "A fine likeness. Much safer at this scale."

-- WALANI
STRINGS.CHARACTERS.WALANI.DESCRIBE.BEEQUEEN = "Whoa, big mama buzz is not vibin' with me."
STRINGS.CHARACTERS.WALANI.DESCRIBE.BEEQUEENHIVE.GENERIC = "Sticky ground? Hard pass."
STRINGS.CHARACTERS.WALANI.DESCRIBE.BEEQUEENHIVE.GROWING = "Pretty sure that wasn't that huge a minute ago."
STRINGS.CHARACTERS.WALANI.DESCRIBE.BEEQUEENHIVEGROWN = "Yeah nah, that's officially too much hive."
STRINGS.CHARACTERS.WALANI.DESCRIBE.CHESSPIECE_BEEQUEEN = "At least this queen can't chase me."

-- WARBUCKS
STRINGS.CHARACTERS.WARBUCKS.DESCRIBE.BEEQUEEN = "I say! That is a most formidable sovereign."
STRINGS.CHARACTERS.WARBUCKS.DESCRIBE.BEEQUEENHIVE.GENERIC = "An unpleasantly sticky affair. Ruinous to one's footwear."
STRINGS.CHARACTERS.WARBUCKS.DESCRIBE.BEEQUEENHIVE.GROWING = "Curious. The colony appears to be expanding its holdings."
STRINGS.CHARACTERS.WARBUCKS.DESCRIBE.BEEQUEENHIVEGROWN = "Good lord. That hive has become positively monstrous."
STRINGS.CHARACTERS.WARBUCKS.DESCRIBE.CHESSPIECE_BEEQUEEN = "A charming tribute, provided it stays quite still."

-- WHEELER
STRINGS.CHARACTERS.WHEELER.DESCRIBE.BEEQUEEN = "Okay, that is way too many bees in one bee."
STRINGS.CHARACTERS.WHEELER.DESCRIBE.BEEQUEENHIVE.GENERIC = "If I step in that, I'm never getting unstuck."
STRINGS.CHARACTERS.WHEELER.DESCRIBE.BEEQUEENHIVE.GROWING = "Uh... it definitely looks bigger than before."
STRINGS.CHARACTERS.WHEELER.DESCRIBE.BEEQUEENHIVEGROWN = "Nope! That is a full-on disaster nest."
STRINGS.CHARACTERS.WHEELER.DESCRIBE.CHESSPIECE_BEEQUEEN = "Much better. Statues don't swarm."

-- WILBA
STRINGS.CHARACTERS.WILBA.DESCRIBE.BEEQUEEN = "BEHOLD! A QUEENE OF STINGES MOST CRUEL."
STRINGS.CHARACTERS.WILBA.DESCRIBE.BEEQUEENHIVE.GENERIC = "WILBA DOST NAUGHT WISH TREAD THIS STICKIE EARTH."
STRINGS.CHARACTERS.WILBA.DESCRIBE.BEEQUEENHIVE.GROWING = "LO! THE HIVE DOTH WAX AND SWELL."
STRINGS.CHARACTERS.WILBA.DESCRIBE.BEEQUEENHIVEGROWN = "IT IS ENORMOUS, AND FULL OF BUZZING WROTH."
STRINGS.CHARACTERS.WILBA.DESCRIBE.CHESSPIECE_BEEQUEEN = "A QUEENE IN STONE, DEPRIV'D OF HER STING."

-- WOODLEGS
STRINGS.CHARACTERS.WOODLEGS.DESCRIBE.BEEQUEEN = "Yarr, that's a right nasty crown o' stingers!"
STRINGS.CHARACTERS.WOODLEGS.DESCRIBE.BEEQUEENHIVE.GENERIC = "That sticky stuff'll steal me boots clean off."
STRINGS.CHARACTERS.WOODLEGS.DESCRIBE.BEEQUEENHIVE.GROWING = "The bees be buildin' up their fort, savvy?"
STRINGS.CHARACTERS.WOODLEGS.DESCRIBE.BEEQUEENHIVEGROWN = "Blimey! That hive's big as a ship's hull!"
STRINGS.CHARACTERS.WOODLEGS.DESCRIBE.CHESSPIECE_BEEQUEEN = "Now that's a queen I don't mind lookin' at."
